"""Backtest planning, runner, and falsifier primitives."""

from silver.backtest.momentum_falsifier import (
    DEFAULT_MIN_TRAIN_SESSIONS,
    DEFAULT_ROUND_TRIP_COST_BPS,
    DEFAULT_STEP_SESSIONS,
    DEFAULT_TEST_SESSIONS,
    MomentumBacktestRow,
    MomentumDateResult,
    MomentumFalsifierInputError,
    MomentumFalsifierResult,
    MomentumHeadlineMetrics,
    MomentumWindowResult,
    run_momentum_falsifier,
)
from silver.backtest.momentum_runner import (
    BacktestSampleCounts,
    BaselineComparison,
    LinearMomentumModel,
    MomentumBacktestConfig,
    MomentumBacktestError,
    MomentumBacktestPrediction,
    MomentumBacktestResult,
    MomentumBacktestSplitResult,
    PersistedForwardReturnLabel,
    PersistedMomentumFeatureValue,
    PredictiveMetrics,
    TransactionCostConfig,
    run_momentum_12_1_backtest,
)
from silver.backtest.walk_forward import (
    WalkForwardConfig,
    WalkForwardConfigError,
    WalkForwardSplit,
    plan_walk_forward_splits,
)

__all__ = [
    "DEFAULT_MIN_TRAIN_SESSIONS",
    "DEFAULT_ROUND_TRIP_COST_BPS",
    "DEFAULT_STEP_SESSIONS",
    "DEFAULT_TEST_SESSIONS",
    "BacktestSampleCounts",
    "BaselineComparison",
    "LinearMomentumModel",
    "MomentumBacktestConfig",
    "MomentumBacktestError",
    "MomentumBacktestPrediction",
    "MomentumBacktestResult",
    "MomentumBacktestRow",
    "MomentumBacktestSplitResult",
    "MomentumDateResult",
    "MomentumFalsifierInputError",
    "MomentumFalsifierResult",
    "MomentumHeadlineMetrics",
    "MomentumWindowResult",
    "PersistedForwardReturnLabel",
    "PersistedMomentumFeatureValue",
    "PredictiveMetrics",
    "TransactionCostConfig",
    "WalkForwardConfig",
    "WalkForwardConfigError",
    "WalkForwardSplit",
    "plan_walk_forward_splits",
    "run_momentum_12_1_backtest",
    "run_momentum_falsifier",
]
